spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL_NEW}
    username: ${SPRING_DATASOURCE_USERNAME_NEW}
    password: ${SPRING_DATASOURCE_PASSWORD_NEW}
  elasticsearch:
    uris: http://elastic:9200
